name:                agda2HVM
version:             0.1.0.0
github:              "githubuser/agda2HVM"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/agda2HVM#readme>

dependencies:
- base ^>=4.15.0.0
- Agda >= 2.6.2.1 && < 2.6.3
- containers >= 0.5.7.1
- deepseq >= 1.4.5
- text >= 1.2.3.1
- mtl >= 2.2.2
- process

library:
  source-dirs: src

executables:
  agda2HVM:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agda2HVM

tests:
  agda2HVM-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agda2HVM

default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - FlexibleInstances
  - MultiParamTypeClasses
  - TypeSynonymInstances
  - LambdaCase
